// app/layout.jsx or app/layout.js (depending on your Next.js version)
import { Inter } from "next/font/google";
import Head from 'next/head'; // Import Head from next/head
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <script
          src="https://www.google.com/recaptcha/api.js?render=your_site_key"
          async
          defer
        ></script>
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
